### ISSUE TITLE
能否提供一下vulntarget-e虚机的密码

### ISSUE THREAD

**Issue by hbhang** [crow821/vulntarget#11]
vulntarget-e 安装环境中没有提供ubuntu、win2008等虚机的密码，可否提供一下。

**Comment by crow821** [comment]
https://mp.weixin.qq.com/s/QWpkYf56oFvNdlumNo6fMA
ubuntu的密码你看下快照信息里面应该是有的
<img width="721" alt="image" src="https://user-images.githubusercontent.com/39254463/196638847-0b4ac9cb-87f0-4ef5-a73f-28c057e9655e.png">

**Comment by hbhang** [comment]
快照下看到密码了，多谢。
