### ISSUE TITLE
e,f的登录密码麻烦告知下，g的网盘失效了，群已满，麻烦再建个群

### ISSUE THREAD

**Issue by Bluecap666** [crow821/vulntarget#16]

**Comment by crow821** [comment]
vulntarget-e的密码信息
![image](https://github.com/crow821/vulntarget/assets/39254463/7600b2d1-d45d-452a-8f5b-e76b0bd89081)
群还在，链接也没有失效，加我WeChat，进群

**Comment by Bluecap666** [comment]
wechat是多少



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月12日(星期一) 下午5:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [crow821/vulntarget] e,f的登录密码麻烦告知下，g的网盘失效了，群已满，麻烦再建个群 (Issue #16)





 
vulntarget-e的密码信息
 
 群还在，链接也没有失效，加我WeChat，进群

**Comment by crow821** [comment]
我github主页有
